AWSTemplateFormatVersion: 2010-09-09
Description: |
  Creates an ELB pointing to an ASG with Specified Min, Max, and desired capacity in each specified
  subnet

Parameters:
  environmentName:
    Description: "Target deployment environment (ci, qa, perf, demo, prod)"
    Type: String
    AllowedValues:
      - ci
      - qa
      - perf
      - demo
      - prod

  branchName:
    Description: Name of the branch
    Type: String

  repoName:
    Description: Name of the repo this stack is deploying on behalf of
    Type: String

  maxSizeASG:
    Description: Max Size for the ASG
    Type: String
    Default: "10"

  minSizeASG:
    Description: Min Size for the ASG
    Type: String
    Default: "2"

  desiredCapacityASG:
    Description: The desired capacity for the ASG
    Type: String
    Default: "2"

  subnetIds:
    Description: List the Subnet Ids of the instances
    Type: CommaDelimitedList

  keyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  instanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro

  instanceSecurityGroups:
    Description: List of Security Group IDs
    Type: CommaDelimitedList

  vpcId:
    Description: The VPC ID
    Type: "AWS::EC2::VPC::Id"

  sshLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: "9"
    MaxLength: "18"
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  RegionMap:
    us-east-1:
      HVM64: ami-0ff8a91507f77f867
    us-west-1:
      HVM64: ami-0bdb828fd58c52235
    us-east-2:
      HVM64: ami-0e38b48473ea57778

Resources:

  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: "1"
        MinInstancesInService: "1"
        PauseTime: PT15M
        WaitOnResourceSignals: "true"
    Properties:
      AutoScalingGroupName: !Join
        - "-"
        - - !Ref environmentName
          - !Ref branchName
          - !Ref repoName
          - ASG
      AvailabilityZones: !GetAZs ""
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      Cooldown: 120
      DesiredCapacity: !Ref desiredCapacityASG
      LaunchConfigurationName: !Ref LaunchConfig
      MaxSize: !Ref maxSizeASG
      MinSize: !Ref minSizeASG
      Tags:
        - Key: environmentName
          Value: !Ref environmentName
          PropagateAtLaunch: "true"
        - Key: branchName
          Value: !Ref branchName
          PropagateAtLaunch: "true"
        - Key: repoName
          Value: !Ref repoName
          PropagateAtLaunch: "true"
      VPCZoneIdentifier: !Ref subnetIds

  ApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Subnets: !Ref subnetIds
      Tags:
        - Key: environmentName
          Value: !Ref environmentName
        - Key: branchName
          Value: !Ref branchName
        - Key: repoName
          Value: !Ref repoName

  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: "80"
      Protocol: HTTP 

  ALBTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref vpcId
      Tags:
        - Key: environmentName
          Value: !Ref environmentName
        - Key: branchName
          Value: !Ref branchName
        - Key: repoName
          Value: !Ref repoName 

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access and HTTP access on the configured port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref sshLocation
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
      VpcId: !Ref vpcId
      Tags:
        - Key: environmentName
          Value: !Ref environmentName
        - Key: branchName
          Value: !Ref branchName
        - Key: repoName
          Value: !Ref repoName 

  LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      KeyName: !Ref keyName
      ImageId: !FindInMap
        - RegionMap
        - !Ref "AWS::Region"
        - HVM64
      SecurityGroups: !Ref instanceSecurityGroups
      InstanceType: !Ref instanceType
      LaunchConfigurationName: !Join
        - "-"
        - - !Ref environmentName
          - !Ref branchName
          - !Ref repoName
          - LaunchConfig

  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      Cooldown: 300
      AutoScalingGroupName:
        Ref: AutoScalingGroup
      ScalingAdjustment: '1'
  
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: '1'
      Statistic: Average
      Threshold: '70'
      AlarmDescription: Alarm if CPU too high or metric disappears indicating instance is down
      Period: '60'
      AlarmActions:
      - Ref: ScaleUpPolicy
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: AutoScalingGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization

  AsgUrlSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${environmentName}-${branchName}-${repoName}/Uri"
      Type: String
      Value: !Join
        - ""
        - - "http://"
          - !GetAtt
            - ApplicationLoadBalancer
            - DNSName
      Description: "URI of the ${environmentName}-${branchName}-${repoName} Service"

Outputs:

  URL:
    Description: URI of the service
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt
          - ApplicationLoadBalancer
          - DNSName

  AutoscalingGroup:
    Description: The newly created asg
    Value: !Ref AutoScalingGroup
    
  LaunchConfig:
    Description: the newly created launch config
    Value: !Ref LaunchConfig
