AWSTemplateFormatVersion: 2010-09-09
Description: Redis ElastiCache Stack

Parameters:

  environmentName:
    Description: "Target deployment environment (ci, qa, perf, demo, prod)"
    Type: String
    AllowedValues:
      - ci
      - qa
      - perf
      - demo
      - prod
    Default: ci
    
  branchName:
    Description: Name of the branch
    Type: String
    Default: master

  repoName:
    Description: Name of the repo this stack is deploying on behalf of
    Type: String

  cacheNodeType:
    Description: Cache node instance class, e.g. cache.t2.micro(free tier). See https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/CacheNodes.SelectSize.html
    Type: String
    Default: cache.t2.micro

  autoMinorVersionUpgrade:
    Description: Whether or not minor version upgrades to the cache engine should be applied automatically during the maintenance window.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  
  subnetIds:
    Description: List the Subnet Ids for the instance
    Type: CommaDelimitedList
  
  vpcId:
    Description: The VPC ID
    Type: "AWS::EC2::VPC::Id"

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ElastiCache Security Group
      VpcId:
        !Ref vpcId
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref environmentName
              - !Ref branchName
              - !Ref repoName
              - ElastiCacheSecurityGroup
        - Key: environmentName
          Value: !Ref environmentName
        - Key: branchName
          Value: !Ref branchName
        - Key: repoName
          Value: !Ref repoName 

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Cache Subnet Group
      SubnetIds: !Ref subnetIds

  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: !Ref autoMinorVersionUpgrade
      Engine: redis
      CacheNodeType: !Ref cacheNodeType
      ClusterName : !Join
        - "-"
        - - !Ref environmentName
          - !Ref branchName
          - !Ref repoName
          - ElastiCacheCluster
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref SubnetGroup
      VpcSecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: !Join
            - "-"
            - - !Ref environmentName
              - !Ref branchName
              - !Ref repoName
              - ElastiCacheCluster
        - Key: environmentName
          Value: !Ref environmentName
        - Key: branchName
          Value: !Ref branchName
        - Key: repoName
          Value: !Ref repoName
  
  ElasticCacheUriSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/${environmentName}-${branchName}-${repoName}/ElasticCacheUri"
      Type: String
      Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address
      Description: "${environmentName}-${branchName}-${repoName} ElasticCache Endpoint"

Outputs:

  ElastiCacheClusterArn:
    Description: ElastiCache Cluster Arn
    Value: !Sub arn:aws:elasticache:${AWS::Region}:${AWS::AccountId}:cluster/${ElastiCacheCluster}

  ElastiCacheClusterId:
    Description: ElastiCache Cluster ID
    Value: !Ref ElastiCacheCluster

  ElastiCacheAddress:
    Description: ElastiCache endpoint address
    Value: !GetAtt ElastiCacheCluster.RedisEndpoint.Address
